/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWorkspacesIndexRouteImport } from './routes/_authenticated/workspaces/index'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/index'
import { Route as AuthenticatedProjectsProjectIdActivityRouteImport } from './routes/_authenticated/projects/$projectId/activity'
import { Route as AuthenticatedProjectsProjectIdContactsRouteImport } from './routes/_authenticated/projects/$projectId/contacts'
import { Route as AuthenticatedProjectsProjectIdOverviewRouteImport } from './routes/_authenticated/projects/$projectId/overview'
import { Route as AuthenticatedProjectsProjectIdTasksRouteImport } from './routes/_authenticated/projects/$projectId/tasks'
import { Route as AuthenticatedWorkspacesWorkspaceIdIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdBoardRouteImport } from './routes/_authenticated/workspaces/$workspaceId/board'
import { Route as AuthenticatedWorkspacesWorkspaceIdSettingsIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/settings/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdSettingsPhasesRouteImport } from './routes/_authenticated/workspaces/$workspaceId/settings/phases'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspacesIndexRoute =
  AuthenticatedWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdActivityRoute =
  AuthenticatedProjectsProjectIdActivityRouteImport.update({
    id: '/projects/$projectId/activity',
    path: '/projects/$projectId/activity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdContactsRoute =
  AuthenticatedProjectsProjectIdContactsRouteImport.update({
    id: '/projects/$projectId/contacts',
    path: '/projects/$projectId/contacts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdOverviewRoute =
  AuthenticatedProjectsProjectIdOverviewRouteImport.update({
    id: '/projects/$projectId/overview',
    path: '/projects/$projectId/overview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdTasksRoute =
  AuthenticatedProjectsProjectIdTasksRouteImport.update({
    id: '/projects/$projectId/tasks',
    path: '/projects/$projectId/tasks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/workspaces/$workspaceId/',
    path: '/workspaces/$workspaceId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdBoardRoute =
  AuthenticatedWorkspacesWorkspaceIdBoardRouteImport.update({
    id: '/workspaces/$workspaceId/board',
    path: '/workspaces/$workspaceId/board',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdSettingsIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdSettingsIndexRouteImport.update({
    id: '/workspaces/$workspaceId/settings/',
    path: '/workspaces/$workspaceId/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdSettingsPhasesRoute =
  AuthenticatedWorkspacesWorkspaceIdSettingsPhasesRouteImport.update({
    id: '/workspaces/$workspaceId/settings/phases',
    path: '/workspaces/$workspaceId/settings/phases',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/projects/$projectId/activity': typeof AuthenticatedProjectsProjectIdActivityRoute
  '/projects/$projectId/contacts': typeof AuthenticatedProjectsProjectIdContactsRoute
  '/projects/$projectId/overview': typeof AuthenticatedProjectsProjectIdOverviewRoute
  '/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRoute
  '/workspaces/$workspaceId/board': typeof AuthenticatedWorkspacesWorkspaceIdBoardRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/settings/phases': typeof AuthenticatedWorkspacesWorkspaceIdSettingsPhasesRoute
  '/workspaces/$workspaceId/settings/': typeof AuthenticatedWorkspacesWorkspaceIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/projects/$projectId/activity': typeof AuthenticatedProjectsProjectIdActivityRoute
  '/projects/$projectId/contacts': typeof AuthenticatedProjectsProjectIdContactsRoute
  '/projects/$projectId/overview': typeof AuthenticatedProjectsProjectIdOverviewRoute
  '/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRoute
  '/workspaces/$workspaceId/board': typeof AuthenticatedWorkspacesWorkspaceIdBoardRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/settings/phases': typeof AuthenticatedWorkspacesWorkspaceIdSettingsPhasesRoute
  '/workspaces/$workspaceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/_authenticated/projects/$projectId/activity': typeof AuthenticatedProjectsProjectIdActivityRoute
  '/_authenticated/projects/$projectId/contacts': typeof AuthenticatedProjectsProjectIdContactsRoute
  '/_authenticated/projects/$projectId/overview': typeof AuthenticatedProjectsProjectIdOverviewRoute
  '/_authenticated/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRoute
  '/_authenticated/workspaces/$workspaceId/board': typeof AuthenticatedWorkspacesWorkspaceIdBoardRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/_authenticated/workspaces/$workspaceId/settings/phases': typeof AuthenticatedWorkspacesWorkspaceIdSettingsPhasesRoute
  '/_authenticated/workspaces/$workspaceId/settings/': typeof AuthenticatedWorkspacesWorkspaceIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/workspaces/'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/contacts'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/tasks'
    | '/workspaces/$workspaceId/board'
    | '/projects/$projectId/'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/settings/phases'
    | '/workspaces/$workspaceId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/workspaces'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/contacts'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/tasks'
    | '/workspaces/$workspaceId/board'
    | '/projects/$projectId'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/settings/phases'
    | '/workspaces/$workspaceId/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/workspaces/'
    | '/_authenticated/projects/$projectId/activity'
    | '/_authenticated/projects/$projectId/contacts'
    | '/_authenticated/projects/$projectId/overview'
    | '/_authenticated/projects/$projectId/tasks'
    | '/_authenticated/workspaces/$workspaceId/board'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/workspaces/$workspaceId/'
    | '/_authenticated/workspaces/$workspaceId/settings/phases'
    | '/_authenticated/workspaces/$workspaceId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthenticatedWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/activity': {
      id: '/_authenticated/projects/$projectId/activity'
      path: '/projects/$projectId/activity'
      fullPath: '/projects/$projectId/activity'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/contacts': {
      id: '/_authenticated/projects/$projectId/contacts'
      path: '/projects/$projectId/contacts'
      fullPath: '/projects/$projectId/contacts'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/overview': {
      id: '/_authenticated/projects/$projectId/overview'
      path: '/projects/$projectId/overview'
      fullPath: '/projects/$projectId/overview'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/tasks': {
      id: '/_authenticated/projects/$projectId/tasks'
      path: '/projects/$projectId/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$workspaceId/': {
      id: '/_authenticated/workspaces/$workspaceId/'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$workspaceId/board': {
      id: '/_authenticated/workspaces/$workspaceId/board'
      path: '/workspaces/$workspaceId/board'
      fullPath: '/workspaces/$workspaceId/board'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdBoardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$workspaceId/settings/': {
      id: '/_authenticated/workspaces/$workspaceId/settings/'
      path: '/workspaces/$workspaceId/settings'
      fullPath: '/workspaces/$workspaceId/settings/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$workspaceId/settings/phases': {
      id: '/_authenticated/workspaces/$workspaceId/settings/phases'
      path: '/workspaces/$workspaceId/settings/phases'
      fullPath: '/workspaces/$workspaceId/settings/phases'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdSettingsPhasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedWorkspacesIndexRoute: typeof AuthenticatedWorkspacesIndexRoute
  AuthenticatedProjectsProjectIdActivityRoute: typeof AuthenticatedProjectsProjectIdActivityRoute
  AuthenticatedProjectsProjectIdContactsRoute: typeof AuthenticatedProjectsProjectIdContactsRoute
  AuthenticatedProjectsProjectIdOverviewRoute: typeof AuthenticatedProjectsProjectIdOverviewRoute
  AuthenticatedProjectsProjectIdTasksRoute: typeof AuthenticatedProjectsProjectIdTasksRoute
  AuthenticatedWorkspacesWorkspaceIdBoardRoute: typeof AuthenticatedWorkspacesWorkspaceIdBoardRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
  AuthenticatedWorkspacesWorkspaceIdIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  AuthenticatedWorkspacesWorkspaceIdSettingsPhasesRoute: typeof AuthenticatedWorkspacesWorkspaceIdSettingsPhasesRoute
  AuthenticatedWorkspacesWorkspaceIdSettingsIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedWorkspacesIndexRoute: AuthenticatedWorkspacesIndexRoute,
  AuthenticatedProjectsProjectIdActivityRoute:
    AuthenticatedProjectsProjectIdActivityRoute,
  AuthenticatedProjectsProjectIdContactsRoute:
    AuthenticatedProjectsProjectIdContactsRoute,
  AuthenticatedProjectsProjectIdOverviewRoute:
    AuthenticatedProjectsProjectIdOverviewRoute,
  AuthenticatedProjectsProjectIdTasksRoute:
    AuthenticatedProjectsProjectIdTasksRoute,
  AuthenticatedWorkspacesWorkspaceIdBoardRoute:
    AuthenticatedWorkspacesWorkspaceIdBoardRoute,
  AuthenticatedProjectsProjectIdIndexRoute:
    AuthenticatedProjectsProjectIdIndexRoute,
  AuthenticatedWorkspacesWorkspaceIdIndexRoute:
    AuthenticatedWorkspacesWorkspaceIdIndexRoute,
  AuthenticatedWorkspacesWorkspaceIdSettingsPhasesRoute:
    AuthenticatedWorkspacesWorkspaceIdSettingsPhasesRoute,
  AuthenticatedWorkspacesWorkspaceIdSettingsIndexRoute:
    AuthenticatedWorkspacesWorkspaceIdSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
