/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as InviteAcceptRouteImport } from './routes/invite.accept'
import { Route as AuthenticatedCompaniesIndexRouteImport } from './routes/_authenticated/companies/index'
import { Route as AuthenticatedCompaniesCompanyIdRouteImport } from './routes/_authenticated/companies/$companyId'
import { Route as AuthenticatedContactsIndexRouteImport } from './routes/_authenticated/contacts/index'
import { Route as AuthenticatedContactsContactIdRouteImport } from './routes/_authenticated/contacts/$contactId'
import { Route as AuthenticatedKbIndexRouteImport } from './routes/_authenticated/kb/index'
import { Route as AuthenticatedKbArticleIdRouteImport } from './routes/_authenticated/kb/$articleId'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedSettingsAuditLogRouteImport } from './routes/_authenticated/settings/audit-log'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings/general'
import { Route as AuthenticatedSettingsMembersRouteImport } from './routes/_authenticated/settings/members'
import { Route as AuthenticatedWorkspacesIndexRouteImport } from './routes/_authenticated/workspaces/index'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/index'
import { Route as AuthenticatedProjectsProjectIdActivityRouteImport } from './routes/_authenticated/projects/$projectId/activity'
import { Route as AuthenticatedProjectsProjectIdContactsRouteImport } from './routes/_authenticated/projects/$projectId/contacts'
import { Route as AuthenticatedProjectsProjectIdFilesRouteImport } from './routes/_authenticated/projects/$projectId/files'
import { Route as AuthenticatedProjectsProjectIdTasksRouteImport } from './routes/_authenticated/projects/$projectId/tasks'
import { Route as AuthenticatedWorkspacesWorkspaceIdIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdBoardRouteImport } from './routes/_authenticated/workspaces/$workspaceId/board'
import { Route as AuthenticatedWorkspacesWorkspaceIdFieldsRouteImport } from './routes/_authenticated/workspaces/$workspaceId/fields'
import { Route as AuthenticatedProjectsProjectIdPagesIndexRouteImport } from './routes/_authenticated/projects/$projectId/pages/index'
import { Route as AuthenticatedProjectsProjectIdPagesPageIdRouteImport } from './routes/_authenticated/projects/$projectId/pages/$pageId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompaniesIndexRoute =
  AuthenticatedCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompaniesCompanyIdRoute =
  AuthenticatedCompaniesCompanyIdRouteImport.update({
    id: '/companies/$companyId',
    path: '/companies/$companyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContactsIndexRoute =
  AuthenticatedContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContactsContactIdRoute =
  AuthenticatedContactsContactIdRouteImport.update({
    id: '/contacts/$contactId',
    path: '/contacts/$contactId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKbIndexRoute = AuthenticatedKbIndexRouteImport.update({
  id: '/kb/',
  path: '/kb/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKbArticleIdRoute =
  AuthenticatedKbArticleIdRouteImport.update({
    id: '/kb/$articleId',
    path: '/kb/$articleId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAuditLogRoute =
  AuthenticatedSettingsAuditLogRouteImport.update({
    id: '/settings/audit-log',
    path: '/settings/audit-log',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsMembersRoute =
  AuthenticatedSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesIndexRoute =
  AuthenticatedWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdActivityRoute =
  AuthenticatedProjectsProjectIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdContactsRoute =
  AuthenticatedProjectsProjectIdContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdFilesRoute =
  AuthenticatedProjectsProjectIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdTasksRoute =
  AuthenticatedProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/workspaces/$workspaceId/',
    path: '/workspaces/$workspaceId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdBoardRoute =
  AuthenticatedWorkspacesWorkspaceIdBoardRouteImport.update({
    id: '/workspaces/$workspaceId/board',
    path: '/workspaces/$workspaceId/board',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdFieldsRoute =
  AuthenticatedWorkspacesWorkspaceIdFieldsRouteImport.update({
    id: '/workspaces/$workspaceId/fields',
    path: '/workspaces/$workspaceId/fields',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdPagesIndexRoute =
  AuthenticatedProjectsProjectIdPagesIndexRouteImport.update({
    id: '/pages/',
    path: '/pages/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdPagesPageIdRoute =
  AuthenticatedProjectsProjectIdPagesPageIdRouteImport.update({
    id: '/pages/$pageId',
    path: '/pages/$pageId',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdRoute
  '/contacts/$contactId': typeof AuthenticatedContactsContactIdRoute
  '/kb/$articleId': typeof AuthenticatedKbArticleIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/settings/audit-log': typeof AuthenticatedSettingsAuditLogRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/contacts/': typeof AuthenticatedContactsIndexRoute
  '/kb/': typeof AuthenticatedKbIndexRoute
  '/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/projects/$projectId/activity': typeof AuthenticatedProjectsProjectIdActivityRoute
  '/projects/$projectId/contacts': typeof AuthenticatedProjectsProjectIdContactsRoute
  '/projects/$projectId/files': typeof AuthenticatedProjectsProjectIdFilesRoute
  '/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRoute
  '/workspaces/$workspaceId/board': typeof AuthenticatedWorkspacesWorkspaceIdBoardRoute
  '/workspaces/$workspaceId/fields': typeof AuthenticatedWorkspacesWorkspaceIdFieldsRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/projects/$projectId/pages/$pageId': typeof AuthenticatedProjectsProjectIdPagesPageIdRoute
  '/projects/$projectId/pages/': typeof AuthenticatedProjectsProjectIdPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdRoute
  '/contacts/$contactId': typeof AuthenticatedContactsContactIdRoute
  '/kb/$articleId': typeof AuthenticatedKbArticleIdRoute
  '/settings/audit-log': typeof AuthenticatedSettingsAuditLogRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/contacts': typeof AuthenticatedContactsIndexRoute
  '/kb': typeof AuthenticatedKbIndexRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/projects/$projectId/activity': typeof AuthenticatedProjectsProjectIdActivityRoute
  '/projects/$projectId/contacts': typeof AuthenticatedProjectsProjectIdContactsRoute
  '/projects/$projectId/files': typeof AuthenticatedProjectsProjectIdFilesRoute
  '/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRoute
  '/workspaces/$workspaceId/board': typeof AuthenticatedWorkspacesWorkspaceIdBoardRoute
  '/workspaces/$workspaceId/fields': typeof AuthenticatedWorkspacesWorkspaceIdFieldsRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/projects/$projectId/pages/$pageId': typeof AuthenticatedProjectsProjectIdPagesPageIdRoute
  '/projects/$projectId/pages': typeof AuthenticatedProjectsProjectIdPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdRoute
  '/_authenticated/contacts/$contactId': typeof AuthenticatedContactsContactIdRoute
  '/_authenticated/kb/$articleId': typeof AuthenticatedKbArticleIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/settings/audit-log': typeof AuthenticatedSettingsAuditLogRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/_authenticated/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/_authenticated/contacts/': typeof AuthenticatedContactsIndexRoute
  '/_authenticated/kb/': typeof AuthenticatedKbIndexRoute
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/_authenticated/projects/$projectId/activity': typeof AuthenticatedProjectsProjectIdActivityRoute
  '/_authenticated/projects/$projectId/contacts': typeof AuthenticatedProjectsProjectIdContactsRoute
  '/_authenticated/projects/$projectId/files': typeof AuthenticatedProjectsProjectIdFilesRoute
  '/_authenticated/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRoute
  '/_authenticated/workspaces/$workspaceId/board': typeof AuthenticatedWorkspacesWorkspaceIdBoardRoute
  '/_authenticated/workspaces/$workspaceId/fields': typeof AuthenticatedWorkspacesWorkspaceIdFieldsRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/_authenticated/projects/$projectId/pages/$pageId': typeof AuthenticatedProjectsProjectIdPagesPageIdRoute
  '/_authenticated/projects/$projectId/pages/': typeof AuthenticatedProjectsProjectIdPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/invite/accept'
    | '/companies/$companyId'
    | '/contacts/$contactId'
    | '/kb/$articleId'
    | '/projects/$projectId'
    | '/settings/audit-log'
    | '/settings/general'
    | '/settings/members'
    | '/companies/'
    | '/contacts/'
    | '/kb/'
    | '/workspaces/'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/contacts'
    | '/projects/$projectId/files'
    | '/projects/$projectId/tasks'
    | '/workspaces/$workspaceId/board'
    | '/workspaces/$workspaceId/fields'
    | '/projects/$projectId/'
    | '/workspaces/$workspaceId/'
    | '/projects/$projectId/pages/$pageId'
    | '/projects/$projectId/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/invite/accept'
    | '/companies/$companyId'
    | '/contacts/$contactId'
    | '/kb/$articleId'
    | '/settings/audit-log'
    | '/settings/general'
    | '/settings/members'
    | '/companies'
    | '/contacts'
    | '/kb'
    | '/workspaces'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/contacts'
    | '/projects/$projectId/files'
    | '/projects/$projectId/tasks'
    | '/workspaces/$workspaceId/board'
    | '/workspaces/$workspaceId/fields'
    | '/projects/$projectId'
    | '/workspaces/$workspaceId'
    | '/projects/$projectId/pages/$pageId'
    | '/projects/$projectId/pages'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/invite/accept'
    | '/_authenticated/'
    | '/_authenticated/companies/$companyId'
    | '/_authenticated/contacts/$contactId'
    | '/_authenticated/kb/$articleId'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/settings/audit-log'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/members'
    | '/_authenticated/companies/'
    | '/_authenticated/contacts/'
    | '/_authenticated/kb/'
    | '/_authenticated/workspaces/'
    | '/_authenticated/projects/$projectId/activity'
    | '/_authenticated/projects/$projectId/contacts'
    | '/_authenticated/projects/$projectId/files'
    | '/_authenticated/projects/$projectId/tasks'
    | '/_authenticated/workspaces/$workspaceId/board'
    | '/_authenticated/workspaces/$workspaceId/fields'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/workspaces/$workspaceId/'
    | '/_authenticated/projects/$projectId/pages/$pageId'
    | '/_authenticated/projects/$projectId/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  InviteAcceptRoute: typeof InviteAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/invite/accept': {
      id: '/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/companies/': {
      id: '/_authenticated/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthenticatedCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies/$companyId': {
      id: '/_authenticated/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts/': {
      id: '/_authenticated/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthenticatedContactsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts/$contactId': {
      id: '/_authenticated/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AuthenticatedContactsContactIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kb/': {
      id: '/_authenticated/kb/'
      path: '/kb'
      fullPath: '/kb/'
      preLoaderRoute: typeof AuthenticatedKbIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kb/$articleId': {
      id: '/_authenticated/kb/$articleId'
      path: '/kb/$articleId'
      fullPath: '/kb/$articleId'
      preLoaderRoute: typeof AuthenticatedKbArticleIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/audit-log': {
      id: '/_authenticated/settings/audit-log'
      path: '/settings/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof AuthenticatedSettingsAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/members': {
      id: '/_authenticated/settings/members'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthenticatedSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthenticatedWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/activity': {
      id: '/_authenticated/projects/$projectId/activity'
      path: '/activity'
      fullPath: '/projects/$projectId/activity'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdActivityRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/contacts': {
      id: '/_authenticated/projects/$projectId/contacts'
      path: '/contacts'
      fullPath: '/projects/$projectId/contacts'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdContactsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/files': {
      id: '/_authenticated/projects/$projectId/files'
      path: '/files'
      fullPath: '/projects/$projectId/files'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdFilesRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/tasks': {
      id: '/_authenticated/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTasksRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/': {
      id: '/_authenticated/workspaces/$workspaceId/'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$workspaceId/board': {
      id: '/_authenticated/workspaces/$workspaceId/board'
      path: '/workspaces/$workspaceId/board'
      fullPath: '/workspaces/$workspaceId/board'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdBoardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$workspaceId/fields': {
      id: '/_authenticated/workspaces/$workspaceId/fields'
      path: '/workspaces/$workspaceId/fields'
      fullPath: '/workspaces/$workspaceId/fields'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdFieldsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/pages/': {
      id: '/_authenticated/projects/$projectId/pages/'
      path: '/pages'
      fullPath: '/projects/$projectId/pages/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPagesIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/pages/$pageId': {
      id: '/_authenticated/projects/$projectId/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/projects/$projectId/pages/$pageId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPagesPageIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdActivityRoute: typeof AuthenticatedProjectsProjectIdActivityRoute
  AuthenticatedProjectsProjectIdContactsRoute: typeof AuthenticatedProjectsProjectIdContactsRoute
  AuthenticatedProjectsProjectIdFilesRoute: typeof AuthenticatedProjectsProjectIdFilesRoute
  AuthenticatedProjectsProjectIdTasksRoute: typeof AuthenticatedProjectsProjectIdTasksRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
  AuthenticatedProjectsProjectIdPagesPageIdRoute: typeof AuthenticatedProjectsProjectIdPagesPageIdRoute
  AuthenticatedProjectsProjectIdPagesIndexRoute: typeof AuthenticatedProjectsProjectIdPagesIndexRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdActivityRoute:
      AuthenticatedProjectsProjectIdActivityRoute,
    AuthenticatedProjectsProjectIdContactsRoute:
      AuthenticatedProjectsProjectIdContactsRoute,
    AuthenticatedProjectsProjectIdFilesRoute:
      AuthenticatedProjectsProjectIdFilesRoute,
    AuthenticatedProjectsProjectIdTasksRoute:
      AuthenticatedProjectsProjectIdTasksRoute,
    AuthenticatedProjectsProjectIdIndexRoute:
      AuthenticatedProjectsProjectIdIndexRoute,
    AuthenticatedProjectsProjectIdPagesPageIdRoute:
      AuthenticatedProjectsProjectIdPagesPageIdRoute,
    AuthenticatedProjectsProjectIdPagesIndexRoute:
      AuthenticatedProjectsProjectIdPagesIndexRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCompaniesCompanyIdRoute: typeof AuthenticatedCompaniesCompanyIdRoute
  AuthenticatedContactsContactIdRoute: typeof AuthenticatedContactsContactIdRoute
  AuthenticatedKbArticleIdRoute: typeof AuthenticatedKbArticleIdRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
  AuthenticatedSettingsAuditLogRoute: typeof AuthenticatedSettingsAuditLogRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsMembersRoute: typeof AuthenticatedSettingsMembersRoute
  AuthenticatedCompaniesIndexRoute: typeof AuthenticatedCompaniesIndexRoute
  AuthenticatedContactsIndexRoute: typeof AuthenticatedContactsIndexRoute
  AuthenticatedKbIndexRoute: typeof AuthenticatedKbIndexRoute
  AuthenticatedWorkspacesIndexRoute: typeof AuthenticatedWorkspacesIndexRoute
  AuthenticatedWorkspacesWorkspaceIdBoardRoute: typeof AuthenticatedWorkspacesWorkspaceIdBoardRoute
  AuthenticatedWorkspacesWorkspaceIdFieldsRoute: typeof AuthenticatedWorkspacesWorkspaceIdFieldsRoute
  AuthenticatedWorkspacesWorkspaceIdIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCompaniesCompanyIdRoute: AuthenticatedCompaniesCompanyIdRoute,
  AuthenticatedContactsContactIdRoute: AuthenticatedContactsContactIdRoute,
  AuthenticatedKbArticleIdRoute: AuthenticatedKbArticleIdRoute,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
  AuthenticatedSettingsAuditLogRoute: AuthenticatedSettingsAuditLogRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsMembersRoute: AuthenticatedSettingsMembersRoute,
  AuthenticatedCompaniesIndexRoute: AuthenticatedCompaniesIndexRoute,
  AuthenticatedContactsIndexRoute: AuthenticatedContactsIndexRoute,
  AuthenticatedKbIndexRoute: AuthenticatedKbIndexRoute,
  AuthenticatedWorkspacesIndexRoute: AuthenticatedWorkspacesIndexRoute,
  AuthenticatedWorkspacesWorkspaceIdBoardRoute:
    AuthenticatedWorkspacesWorkspaceIdBoardRoute,
  AuthenticatedWorkspacesWorkspaceIdFieldsRoute:
    AuthenticatedWorkspacesWorkspaceIdFieldsRoute,
  AuthenticatedWorkspacesWorkspaceIdIndexRoute:
    AuthenticatedWorkspacesWorkspaceIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  InviteAcceptRoute: InviteAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
